name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version: '1.22'
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: '~> v1'
          install-only: true
      - name: Run GoReleaser
        run: make publish-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ASCENTSTREAM_GITHUB_TOKEN }}
          GOVERSION: ${{ steps.setup-go.outputs.go-version }}

  publish-image:
    needs: publish-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download GitHub Release
        run: gh release download "$GITHUB_REF_NAME" --pattern "*-linux-*" --repo "$GITHUB_REPOSITORY" --dir dist
        env:
          GH_TOKEN: ${{ secrets.ASCENTSTREAM_GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - name: Build and push image
        run: IMAGE_NAME="${IMAGE_ORIGIN_NAME}:${GITHUB_REF_NAME#v}" make publish-image
        env:
          IMAGE_ORIGIN_NAME: docker.io/ascentstream/pulsarctl
          IMAGE_CREDS: "${{ secrets.ASCENTSTREAM_DOCKER_USERNAME }}:${{ secrets.ASCENTSTREAM_DOCKER_PASSWORD }}"
